#!/usr/bin/env fish

begin

  set -l IP (cat super_secret_bot_ip.txt)

  echo "[deploy] building..."
  cargo build --release

  echo "[deploy] deploying..."
  scp -r ./resources/* $IP:./deano/resources/
  scp ./target/release/deano $IP:./deano/deano

  echo "[deploy] restarting..."
  ssh -t $IP screen -S deano -X stuff '^C'
  ssh -t $IP screen -S deano -X stuff './deano\\\\n'

  echo "[deploy] done :)"
end
